README.rst
rhg_compute_tools/kubernetes.py
tests/resources/worker_template.yml
tests/test_rhg_compute_tools.py
tox.ini

This PR includes the following modifications:
* `get_worker` is renamed `get_cluster`
* Default parameters to `get_cluster` are pulled from `worker_template.yml` rather than overwritten. this is super important to allow for different cluster specifications on [compute.rhg](https://compute.rhg.com), [compute-test.rhg](https://compute-test.rhg.com), and [compute.impactlab](https://compute.impactlab.org).
* Helper functions to create different cluster flavors are created (`get_micro_cluster`, `get_standard_cluster`, `get_big_cluster`, `get_giant_cluster`).

Addl worker updates

---

rhg_compute_tools/kubernetes.py
tests/test_rhg_compute_tools.py

Bug fix in kubernetes.get_cluster:
resources/requests memory amount should be specified in `'G'` not `'GB'`

bug fix in kubernetes.get_cluster

---

requirements_dev.txt

Updates `cp_to_gcs` and `sync_to_gcs` to `cp_gcs` and `sync_gcs` in order to enable copying/syncing to and from gcs.

update sync_gcs cp_gcs to go bidirectional

---

rhg_compute_tools/kubernetes.py

Adds ``cred_name`` argument to ``rhg_compute_tools.kubernetes.create_cluster()``, which is equivalent to ``cred_path='/opt/gcsfuse_tokens/{}.json'.format(cred_name)``.

add cred_name argument to create_cluster

---

rhg_compute_tools/gcs.py

Adds a function `replicate_directory_structure_on_gcs` which replicates a local directory structure on google cloud storage
@brews give this a spin

Add function replicate_directory_structure_on_gcs

---

HISTORY.rst
requirements.txt
requirements_dev.txt
rhg_compute_tools/cli.py
rhg_compute_tools/gcs.py
setup.py
tests/test_cli.py

This adds basic structure for CLI tools. I used a CLI version of `replicate_directory_structure_on_gcs()` as a starting point.
Here is how it works. Assuming the user installed via pip or conda or whatever. Open command line and run
```
rctools gcs repdirstruc dir1 gs://my-gcs-bucket/
```
Which copies any nested directory structure in "dir1" into "gs://my-gcs-bucket/". You can see help with
```
rctools gcs repdirstruc --help
```
and this works for all subcommands, so
```
rctools --help
```
will list and briefly describe all of the subcommands available.
Note that I had to extend `replicate_directory_structure_on_gcs()` and change its signature so that it now takes an optional authorized client *or a path to GCS credentials* for the `client_or_creds` arg.
This PR also has a few other minor …

WIP: Add CLI for `replicate_directory_structure_on_gcs()`

---

HISTORY.rst
rhg_compute_tools/cli.py
rhg_compute_tools/gcs.py
tests/test_cli.py

This PR presents an alternative approach to PR #49. 
I refactored how we create authenticated clients. Minor refactor to how we mock the CLI tests. Reverted the earlier change to `rhg_compute_tools.gcs.replicate_directory_structure_on_gcs()` signature -- here it no longer accepting certificates and requires an authenticated client on input. This client is created with `rhg_compute_tools.gcs._authenticate_client()` which reads from a path to credentials or use alternative authentication internal to `cloud.google.storage`.
I feel like this makes the process less magical and flexible enough for future development.

Alternative approach to enable alt GCS auth

---

.gitignore
HISTORY.rst
rhg_compute_tools/__init__.py
rhg_compute_tools/kubernetes.py
setup.py

* Add remote scheduler deployment (part of dask_kubernetes 0.10)
* Remove extraneous `GCSFUSE_TOKENS` env var no longer used in new worker images
* Set library thread limits based on how many cpus are available for a single dask thread
* Change formatting of the extra `env_items` passed to `get_cluster` to be a list rather than a list of dict-like name/value pairs

integrate remote scheduler

---

rhg_compute_tools/kubernetes.py

To create cluster which will spin up workers with custom labels and tolerations:
```python
client, cluster = rhgk.get_cluster(
extra_worker_labels={
'project': 'my-project',
'phase': 'phase2',
'job': 'my-big-distributed-job',
},
extra_pod_tolerations=[
{
"effect": "NoSchedule",
"key": "k8s.dask.org_dedicated",
"operator": "Equal",
"value": "worker-highcpu",
},
{
"effect": "NoSchedule",
"key": "k8s.dask.org/dedicated",
"operator": "Equal",
"value": "worker-highcpu",
},
],
)
```

Allow labels and tolerations in get_cluster

---

requirements_dev.txt
rhg_compute_tools/xarray.py
tests/fixtures.py
tests/test_cli.py

Fixes pytest CI failure due to pytest changing policy on allowing fixture re-declaration in testing modules.

move fixtures into separate module

---

.gitignore
HISTORY.rst
docs/rhg_compute_tools.design.rst
rhg_compute_tools/gcs.py

Make the gsutil API consistent, so that we have `cp`, `sync` and `rm`, each of which accept the same args and kwargs. There are errors raised by travis for other modules.

make gsutil API consistent

---

docs/conf.py
rhg_compute_tools/cli.py
rhg_compute_tools/design/__init__.py
rhg_compute_tools/design/colors.py
rhg_compute_tools/design/plotting.py
rhg_compute_tools/gcs.py
rhg_compute_tools/kubernetes.py
rhg_compute_tools/utils.py
rhg_compute_tools/xarray.py
setup.py
tests/fixtures.py
tests/test_cli.py
tests/test_design.py
travis_pypi_setup.py

OK @delgadom i knowwww you don't like to mix formatter changes and other changes, but #65 actually fixed one of the two bugs I had noticed. The only other one was that warnings was not imported in kubernetes.py but was potentially being called. So this PR contains that one change, and other than that I just called `isort --profile black .` and added all those changes (isort v5 now has profiles so you can make sure that isort doesn't do anything that black would then revert). Importantly it doesn't mess up the importing AFTER sys.path in `conf.py`.
Fixes #75

isort everything + 1 change

---

HISTORY.rst
rhg_compute_tools/__init__.py
setup.cfg
setup.py

We used to handle versioning with `bumpversion`, this PR switches it to `setuptools_scm` because it's better maintained.

switch bumpversion to setuptools_scm

---

HISTORY.rst
rhg_compute_tools/xarray.py

Gather `dict(ds.coords)` instead of `ds.coords` (see #83)

address strange memory blowup with rhg_compute_tools.xarray.dataarrays_from_delayed

---

setup.cfg

Without this PR, our configs tell `flake8` to both include and ignore `docs`.
This PR prevents `flake8` from dealing with the contradiction by gathering and gaining sentience to wiping out all humanity.

Minor fix to contradicting flake8 config rule

---

HISTORY.rst
rhg_compute_tools/xarray.py

The file I modified passes the `flake8` test but I did not touch the rest of the files. No new tests needed as this does not change behavior, just speeds things up. Previously, we were calling `client.submit(task).result()` a whole bunch of times in succession. The change is to just call `client.gather()` once rather than all of the `Future.result()` calls.

speed up metadata pulls

---

HISTORY.rst
rhg_compute_tools/design/__init__.py

Updates:
* Don't rebuild matplotlib cache on ``design.__init__``. That does seem like a questionable strategy anyway. Note we still need to figure out how to enable rhg styles/fonts :(

drop matplotlib rebuild() call in deign.__init__

---

HISTORY.rst
requirements.txt
rhg_compute_tools/utils.py
tests/test_rhg_compute_tools.py

Added a decorator to execute a function with timeout features, either locally or from a dask worker.

add retry func

---

HISTORY.rst
rhg_compute_tools/xarray.py
tests/set_gateway_config.py
tests/test_rhg_compute_tools.py

Add the ability to pass kwargs to `client.submit` and `client.gather` as part of the `rhg_compute_tools.xarray` functions. I came across a situation where I wanted to pass the `priority` kwarg, so figured we might as well add the ability to pass any arbitrary kwarg here.

add dask kwargs

---

HISTORY.rst
rhg_compute_tools/gcs.py

rhg_compute_tools.gcs.cp should raise an error when the subprocess call to gsutil fails. this checks the status code and raises if nonzero.

raise for nonzero gsutil status code in cp
